//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Zeus.Common.DataAccess.Entities;
    
namespace TPS.WeiXin.DataAccess.Entities
{
    
    [DataContract(IsReference = true)]
    public partial class Account: IEntityBase
    {
        #region 基本属性
    
    	///<summary>
    	///ID
    	///</summary>
        [DataMember]
        public System.Guid ID { get; set; }
    	///<summary>
    	///微信号
    	///</summary>
        [DataMember]
        public string WeiXinNum { get; set; }
    	///<summary>
    	///AppID
    	///</summary>
        [DataMember]
        public string AppID { get; set; }
    	///<summary>
    	///AppSecret
    	///</summary>
        [DataMember]
        public string AppSecret { get; set; }
    	///<summary>
    	///Token
    	///</summary>
        [DataMember]
        public string Token { get; set; }
    

        #endregion

    }
}
