//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Zeus.Common.DataAccess.Entities;
    
namespace TPS.WeiXin.DataAccess.Entities
{
    
    [DataContract(IsReference = true)]
    public partial class CustomMenu: IEntityBase
    {
        #region 基本属性
    
    	///<summary>
    	///ID
    	///</summary>
        [DataMember]
        public System.Guid ID { get; set; }
    	///<summary>
    	///菜单名
    	///</summary>
        [DataMember]
        public string Name { get; set; }
    	///<summary>
    	///菜单类型 1、点击推事件 2、跳转Url
    	///</summary>
        [DataMember]
        public int Type { get; set; }
    	///<summary>
    	///父级菜单ID
    	///</summary>
        [DataMember]
        public Nullable<System.Guid> ParentMenuID { get; set; }
    	///<summary>
    	///菜单Key值
    	///</summary>
        [DataMember]
        public string Key { get; set; }
    	///<summary>
    	///跳转Url
    	///</summary>
        [DataMember]
        public string View_Url { get; set; }
    	///<summary>
    	///类型全名
    	///</summary>
        [DataMember]
        public string TypeFullName { get; set; }
    	///<summary>
    	///数据状态
    	///</summary>
        [DataMember]
        public int Status { get; set; }
    	///<summary>
    	///账户ID
    	///</summary>
        [DataMember]
        public System.Guid AccountID { get; set; }
    	///<summary>
    	///排序
    	///</summary>
        [DataMember]
        public int Sort { get; set; }
    	///<summary>
    	///创建时间
    	///</summary>
        [DataMember]
        public System.DateTime CreateTime { get; set; }
    

        #endregion

    }
}
