//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Zeus.Common.DataAccess.Entities;
    
namespace TPS.WeiXin.DataAccess.Entities
{
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Reply))]
    public partial class Message: IEntityBase
    {
        public Message()
        {
            this.Reply = new HashSet<Reply>();
        }
    
        #region 基本属性
    
    	///<summary>
    	///ID
    	///</summary>
        [DataMember]
        public System.Guid ID { get; set; }
    	///<summary>
    	///内容
    	///</summary>
        [DataMember]
        public string Content { get; set; }
    	///<summary>
    	///是否是模板
    	///</summary>
        [DataMember]
        public bool IsTemplate { get; set; }
    	///<summary>
    	///类型 0、文本 1、图文 
    	///</summary>
        [DataMember]
        public int Type { get; set; }
    

        #endregion

        #region 导航属性
    
     	[DataMember]
        public virtual ICollection<Reply> Reply { get; set; }
    

        #endregion

    }
}
