//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Zeus.Common.DataAccess.Entities;
    
namespace TPS.WeiXin.DataAccess.Entities
{
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Message))]
    public partial class Reply: IEntityBase
    {
        #region 基本属性
    
    	///<summary>
    	///ID
    	///</summary>
        [DataMember]
        public System.Guid ID { get; set; }
    	///<summary>
    	///回复关键字
    	///</summary>
        [DataMember]
        public string Key { get; set; }
    	///<summary>
    	///关键字类型 0、关键字 1、点击
    	///</summary>
        [DataMember]
        public int KeyType { get; set; }
    	///<summary>
    	///数据状态
    	///</summary>
        [DataMember]
        public int Status { get; set; }
    	///<summary>
    	///账号ID
    	///</summary>
        [DataMember]
        public System.Guid AccountID { get; set; }
    	///<summary>
    	///类型全名
    	///</summary>
        [DataMember]
        public string TypeFullName { get; set; }
    	///<summary>
    	///无描述
    	///</summary>
        [DataMember]
        public System.Guid MessageID { get; set; }
    

        #endregion

        #region 导航属性
    
    	[DataMember]
        public virtual Message Message { get; set; }
    

        #endregion

    }
}
